use strict;
use warnings;
use Module::Build;

my $builder = Module::Build->new(
    module_name         => 'Schedule::Pluggable',
    license             => 'perl',
    dist_author         => 'Tony Edwardson <Tony@Edwardson.co.uk>',
    dist_version_from   => 'lib/Schedule/Pluggable.pm',
    requires => {
	'perl' => 5.008001,
        'Moose' => 0,
        'MooseX::Workers' => 0,
        'MooseX::Object::Pluggable' => 0,
        'Test::More' => 0,
        'version'    => 0,
    },
    add_to_cleanup      => [ 'Schedule-Pluggable-*' ],
);

$builder->create_build_script();
