use strict;
use warnings;
use ExtUtils::MakeMaker;
use 5.008001;

WriteMakefile(
    NAME                => 'Schedule::Pluggable',
    AUTHOR              => 'Tony Edwardson <tony@edwardson.co.uk>',
    VERSION_FROM        => 'lib/Schedule/Pluggable.pm',
    ABSTRACT_FROM       => 'lib/Schedule/Pluggable.pm',
    PL_FILES            => {},
    PREREQ_PM => {
        'Moose' => 0,
        'MooseX::Workers' => 0,
        'MooseX::Object::Pluggable' => 0,
        'Test::More' => 0,
        'version'    => 0,
    },
    dist                => { COMPRESS => 'gzip -9f', SUFFIX => 'gz', },
    clean               => { FILES => 'Schedule--Pluggable-*' },
);
